# Generated by Django 4.2.4 on 2023-10-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_carrinho_produtocodigo_and_more'),
        ('carrinho', '0003_opcaopagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PorcentagemPedido', models.IntegerField(default=0)),
                ('CarrinhoCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carrinho')),
            ],
        ),
    ]
