# Generated by Django 4.2.4 on 2023-10-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='Cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
