# Generated by Django 4.2.4 on 2023-09-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='endereco',
        ),
    ]
