# Generated by Django 4.2.4 on 2023-09-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ProdutoCodigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
