# Generated by Django 4.2.4 on 2023-09-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='produtos')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ProdutoImagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='ProdutoImagem',
            field=models.ManyToManyField(to='home.imagem'),
        ),
    ]
