# Generated by Django 4.2.4 on 2023-09-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_imagem_remove_produto_produtoimagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
