# Generated by Django 4.2.4 on 2023-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_produto_produtoimagem_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='Ativo',
            field=models.BooleanField(default=True),
        ),
    ]
