# Generated by Django 4.2.4 on 2023-10-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_carrinho_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='ProdutoCodigo',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='Quantidade',
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('CarrinhoCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='home.carrinho')),
                ('ProdutoCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto')),
            ],
        ),
    ]
