# Generated by Django 4.2.4 on 2023-10-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_produto_produtodescricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ProdutoNome',
            field=models.CharField(max_length=55),
        ),
    ]
